### ISSUE TITLE
Error installing/building 

### ISSUE THREAD

**Issue by shortbloke** [jamesbulpin/meshblu-connector-ws2811#1]
James, I've a clean install of Raspbian Jessie, installed npm and then ran the command per the readme. It fails, any ideas per below? 

I also tried the parent project rpi-ws281x-native​ and it fails in the same way. However, if I follow the install from source option from here: https://www.npmjs.com/package/rpi-ws281x-native it works for rpi-ws291x-native but the same approach doesn't work with your current branch.

- npm: 1.4.21
- node: v0.10.29
- node-gyp: v3.6.2
- system: Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

```
pi@raspberrypi:~ $ sudo npm install meshblu-connector-ws2811
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
-
> rpi-ws281x-native@0.8.2 install /home/pi/node_modules/meshblu-connector-ws2811/node_modules/rpi-ws281x-native
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/meshblu-connector-ws2811/node_modules/rpi-ws281x-native/build'
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/ws2811.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/pwm.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/dma.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/mailbox.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/board_info.o
  AR(target) Release/obj.target/rpi_libws2811.a
  COPY Release/rpi_libws2811.a
  CXX(target) Release/obj.target/rpi_ws281x/src/rpi-ws281x.o
In file included from ../src/rpi-ws281x.cc:1:0:
../node_modules/nan/nan.h:326:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
rpi_ws281x.target.mk:85: recipe for target 'Release/obj.target/rpi_ws281x/src/rpi-ws281x.o' failed
make: *** [Release/obj.target/rpi_ws281x/src/rpi-ws281x.o] Error 1
make: Leaving directory '/home/pi/node_modules/meshblu-connector-ws2811/node_modules/rpi-ws281x-native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/node_modules/meshblu-connector-ws2811/node_modules/rpi-ws281x-native
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/pi/node_modules/meshblu-connector-ws2811/node_modules/meshblu-connector-schema-generator/node_modules/lodash/fp'
npm ERR! error rolling back  meshblu-connector-ws2811@0.2.2 { [Error: ENOTEMPTY, rmdir '/home/pi/node_modules/meshblu-connector-ws2811/node_modules/meshblu-connector-schema-generator/node_modules/lodash/fp']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/pi/node_modules/meshblu-connector-ws2811/node_modules/meshblu-connector-schema-generator/node_modules/lodash/fp' }
npm ERR! rpi-ws281x-native@0.8.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpi-ws281x-native@0.8.2 install script.
npm ERR! This is most likely a problem with the rpi-ws281x-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls rpi-ws281x-native
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "meshblu-connector-ws2811"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/home/pi/node_modules/meshblu-connector-ws2811/node_modules/meshblu-connector-runner/node_modules/meshblu/node_modules/har-validator/lib/schemas/cache.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "meshblu-connector-ws2811"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/node_modules/meshblu-connector-ws2811/node_modules/meshblu-connector-runner/node_modules/meshblu/node_modules/har-validator/lib/schemas/cache.json
npm ERR! fstream_path /home/pi/node_modules/meshblu-connector-ws2811/node_modules/meshblu-connector-runner/node_modules/meshblu/node_modules/har-validator/lib/schemas/cache.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```
​

**Comment by shortbloke** [comment]
This looks to be the same as: https://github.com/beyondscreen/node-rpi-ws281x-native/issues/51 
So the question is, what is really the minimum version of node needed? 
I suspect I need to raise this issue in the rpi-ws281x-native project.

**Comment by shortbloke** [comment]
Updated node to version v7.10.0 (added extra repository to source this, as not part of the main Jessie repo).
